cmake_minimum_required(VERSION 3.16)
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
	project(kronuz_consensus LANGUAGES CXX)
endif()
add_library(cluster_consensus INTERFACE)
target_include_directories(cluster_consensus INTERFACE "${CMAKE_CURRENT_SOURCE_DIR}/..")
target_compile_features(cluster_consensus INTERFACE cxx_std_20)
add_library(cluster::consensus ALIAS cluster_consensus)

if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
	enable_testing()
	add_executable(consensus_demo demo.cc)
	target_link_libraries(consensus_demo PRIVATE cluster::consensus)
	add_executable(consensus_checkpoint_bench checkpoint_bench.cc)
	target_link_libraries(consensus_checkpoint_bench PRIVATE cluster::consensus)
	add_executable(cluster_consensus_test ../test/consensus_test.cc)
	target_link_libraries(cluster_consensus_test PRIVATE cluster::consensus)
	add_test(NAME cluster_consensus COMMAND cluster_consensus_test)
	set_tests_properties(cluster_consensus PROPERTIES TIMEOUT 30)
	add_executable(cluster_worker_test ../test/worker_test.cc)
	target_link_libraries(cluster_worker_test PRIVATE cluster::consensus)
	add_test(NAME cluster_worker COMMAND cluster_worker_test)
	set_tests_properties(cluster_worker PROPERTIES TIMEOUT 30)
endif()
